env:
  browser: true
  es2021: true
extends: 
  - google
  - plugin:@typescript-eslint/recommended
ignorePatterns:
  - examples/chat-react/
  - examples/
  - dist/
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
rules:
  indent: ["error", 2]
  space-before-function-paren: ["error", "never"]
  quotes: ["error", "single"]
  require-jsdoc: ["warn"]
  valid-jsdoc: ["warn"]
  "@typescript-eslint/no-explicit-any": "warn"
